typography_spectrum: 0.47231
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6875
  lightness: 0.8733611789066344
  saturation: 0.007475039456039667
  rhythmicContrast: 0.5883911431301385
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.87675
analytics:
  google: null
  facebook: null
  twitter: null
name: Alexandertechnique
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: TECHNIQUE ALEXANDER
    id: d4dee4bc-75c0-4b86-93bf-bf350ffa6043
    type: content
favicon: null
title: Technique Alexander Ã  Bruxelles - Martin Michiels
purpose: []
